services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ars
      POSTGRES_PASSWORD: ars_dev_pw
      POSTGRES_DB: ars
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/sql
 
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
 
volumes:
  pgdata: